import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./Components/header";
import Footer from "./Components/footer";

const poppins = Poppins({
  weight: ['400','500', '700'],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['400', '700'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={`${roboto.variable} ${poppins.variable}`}
    >
      <body
        className={` antialiased text-textColor tracking-wider leading-relaxed font-bodyFont bg-whiteColor`}
      >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
